networks:
- name: default
  type: dynamic
  subnets:
  - cloud_properties:
      vlan_ids: [((sl_vlan_public_id)), ((sl_vlan_private_id))]
    dns: [((director_ip)), 8.8.8.8, 10.0.80.11, 10.0.80.12]

resource_pools:
  - name: coreNode
    cloud_properties:
      max_network_speed: 100
      ephemeral_disk_size: 100
      hourly_billing_flag: true
      local_disk_flag: true
      memory: 32768
      cpu: 4
      hostname_prefix: ((deploy_name))-core
      domain: ((sl_vm_domain))
      datacenter: ((sl_datacenter))
    stemcell:
      name: bosh-bluemix-xen-ubuntu-trusty-go_agent
      version: 3468.21.1
  - name: brain
    cloud_properties:
      ephemeral_disk_size: 100
      hourly_billing_flag: true
      local_disk_flag: true
      memory: 8192
      cpu: 4
      hostname_prefix: ((deploy_name))-diego-brain
      domain: ((sl_vm_domain))
      datacenter: ((sl_datacenter))
    stemcell:
      name: bosh-bluemix-xen-ubuntu-trusty-go_agent
      version: 3468.21.1
  - name: cc_bridge
    cloud_properties:
      ephemeral_disk_size: 100
      hourly_billing_flag: true
      local_disk_flag: true
      memory: 8192
      cpu: 4
      hostname_prefix: ((deploy_name))-diego-cc-bridge
      domain: ((sl_vm_domain))
      datacenter: ((sl_datacenter))
    stemcell:
      name: bosh-bluemix-xen-ubuntu-trusty-go_agent
      version: 3468.21.1
  - name: access
    cloud_properties:
      ephemeral_disk_size: 100
      hourly_billing_flag: true
      local_disk_flag: true
      memory: 8192
      cpu: 4
      hostname_prefix: ((deploy_name))-diego-access
      domain: ((sl_vm_domain))
      datacenter: ((sl_datacenter))
    stemcell:
      name: bosh-bluemix-xen-ubuntu-trusty-go_agent
      version: 3468.21.1
  - name: database
    cloud_properties:
      datacenter: ((sl_datacenter))
      ephemeral_disk_size: 100
      hourly_billing_flag: true
      local_disk_flag: true
      memory: 8192
      cpu: 4
      hostname_prefix: ((deploy_name))-diego-db
      domain: softlayer.com
    stemcell:
      name: bosh-bluemix-xen-ubuntu-trusty-go_agent
      version: 3468.21.1
  - name: cell
    cloud_properties:
      datacenter: ((sl_datacenter))
      ephemeral_disk_size: 300
      hourly_billing_flag: true
      local_disk_flag: true
      memory: 32768
      cpu: 4
      hostname_prefix: ((deploy_name))-diego-cell
      domain: softlayer.com
    size: 5
    stemcell:
      name: bosh-bluemix-xen-ubuntu-trusty-go_agent
      version: 3468.21.1
    update:
      canaries: 1
      max_in_flight: 10
  - name: errandsPool
    cloud_properties:
      datacenter: ((sl_datacenter))
      ephemeral_disk_size: 100
      hourly_billing_flag: true
      local_disk_flag: true
      memory: 8192
      cpu: 4
      hostname_prefix: ((deploy_name))-diego-errand
      domain: softlayer.com
    stemcell:
      name: bosh-bluemix-xen-ubuntu-trusty-go_agent
      version: 3468.21.1

disk_types:
- disk_size: 20480
  name: dp_20G

vm_extensions:
  - name: cf-router-network-properties
  - name: cf-tcp-router-network-properties
  - name: diego-ssh-proxy-network-properties
  - name: 50GB_ephemeral_disk
    cloud_properties:
      disk: 51200
  - name: 100GB_ephemeral_disk
    cloud_properties:
      disk: 102400

stemcell_location: https://s3.amazonaws.com/ng-bosh-softlayer-stemcells-bluemix-candidate-container/light-bosh-stemcell-3468.21.1-bluemix-xen-ubuntu-trusty-go_agent.tgz

compilation:
  cloud_properties:
    ephemeral_disk_size: 100
    hourly_billing_flag: true
    memory: 8192
    cpu: 4
    hostname_prefix: ((deploy_name))-worker
    domain: ((sl_vm_domain))
    datacenter: ((sl_datacenter))
  env:
    bosh:
      keep_root_password: true
  network: default
  reuse_compilation_vms: true
  workers: 8
