azs:
- name: z1
  cloud_properties:
    datacenter: ((sl_datacenter))

networks:
- name: default
  type: dynamic
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    azs: [z1]
    dns: [((director_ip)), 8.8.8.8, 10.0.80.11, 10.0.80.12]
    cloud_properties:
      vlan_ids: [((sl_vlan_public_id)), ((sl_vlan_private_id))]

vm_types:
  - name: minimal
    cloud_properties:
      cpu:  1
      memory:  4096
      max_network_speed: 100
      ephemeral_disk_size: 100
      hourly_billing_flag: true
      hostname_prefix: ((sl_vm_name_prefix))
      domain: ((sl_vm_domain))
  - name: small
    cloud_properties:
      cpu:  2
      memory:  8192
      max_network_speed: 100
      ephemeral_disk_size: 100
      hourly_billing_flag: true
      hostname_prefix: ((sl_vm_name_prefix))
      domain: ((sl_vm_domain))
  - name: small-highmem
    cloud_properties:
      cpu:  4
      memory:  32768
      max_network_speed: 100
      ephemeral_disk_size: 100
      hourly_billing_flag: true
      hostname_prefix: ((sl_vm_name_prefix))
      domain: ((sl_vm_domain))
  - name: sharedcpu
    cloud_properties:
      cpu:  1
      memory:  2048
      max_network_speed: 100
      ephemeral_disk_size: 100
      hourly_billing_flag: true
      hostname_prefix: ((sl_vm_name_prefix))
      domain: ((sl_vm_domain))

disk_types:
  - name: default
    disk_size: 100_000
    cloud_properties:
      iops: 3000
      snapshot_space: 10
  - name: small
    disk_size: 20_000
    cloud_properties:
      iops: 500
      snapshot_space: 5
  - name: large
    disk_size: 250_000
    cloud_properties:
      iops: 3000
      snapshot_space: 50
  - disk_size: 5120
    name: 5GB
  - disk_size: 10240
    name: 10GB
  - disk_size: 100240
    name: 100GB

vm_extensions:
  - name: cf-router-network-properties
  - name: cf-tcp-router-network-properties
  - name: diego-ssh-proxy-network-properties
  - name: 50GB_ephemeral_disk
    cloud_properties:
      disk: 51200
  - name: 100GB_ephemeral_disk
    cloud_properties:
      disk: 102400

compilation:
  workers: 5
  reuse_compilation_vms: true
  vm_type: small
  network: default
  az: z1
