azs:
- name: z1
  cloud_properties:
    datacenter: { name: ((sl_datacenter)) }

networks:
- name: default
  type: dynamic
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    azs: [z1]
    dns: [((director_ip)), 8.8.8.8, 10.0.80.11, 10.0.80.12]
    cloud_properties:
      PrimaryNetworkComponent:
        NetworkVlan:
          Id: ((sl_vlan_public))
      PrimaryBackendNetworkComponent:
        NetworkVlan:
          Id: ((sl_vlan_private))

vm_types:
  - name: minimal
    cloud_properties:
      bosh_ip: ((director_ip))
      startCpus:  1
      maxMemory:  4096
      maxMemory: 100
      hourlyBillingFlag: true
      vmNamePrefix: ((sl_vm_name_prefix))
      domain: ((sl_vm_domain))
  - name: small
    cloud_properties:
      bosh_ip: ((director_ip))
      startCpus:  2
      maxMemory:  8192
      maxMemory: 100
      hourlyBillingFlag: true
      vmNamePrefix: ((sl_vm_name_prefix))
      domain: ((sl_vm_domain))
  - name: small-highmem
    cloud_properties:
      bosh_ip: ((director_ip))
      startCpus:  4
      maxMemory:  32768
      maxMemory: 100
      hourlyBillingFlag: true
      vmNamePrefix: ((sl_vm_name_prefix))
      domain: ((sl_vm_domain))
  - name: sharedcpu
    cloud_properties:
      bosh_ip: ((director_ip))
      startCpus:  1
      maxMemory:  2048
      maxMemory: 100
      hourlyBillingFlag: true
      vmNamePrefix: ((sl_vm_name_prefix))
      domain: ((sl_vm_domain))

disk_types:
  - name: default
    disk_size: 100_000
    cloud_properties:
      iops: 3000
  - name: small
    disk_size: 20_000
    cloud_properties:
      iops: 500
  - name: large
    disk_size: 250_000
    cloud_properties:
      iops: 3000
  - disk_size: 5120
    name: 5GB
  - disk_size: 10240
    name: 10GB
  - disk_size: 100240
    name: 100GB

vm_extensions:
  - name: cf-router-network-properties
  - name: cf-tcp-router-network-properties
  - name: diego-ssh-proxy-network-properties
  - name: 50GB_ephemeral_disk
    cloud_properties:
      disk: 51200
  - name: 100GB_ephemeral_disk
    cloud_properties:
      disk: 102400

compilation:
  workers: 5
  reuse_compilation_vms: true
  vm_type: small
  network: default
  az: z1
