azs:
- name: z1
  cloud_properties:
    datacenter: ((sl_datacenter))
- name: z2
  cloud_properties:
    datacenter: ((sl_datacenter))
- name: z3
  cloud_properties:
    datacenter: ((sl_datacenter))

vm_types:
- name: default
  cloud_properties:
    cpu:  4
    memory:  8192
    max_network_speed: 100
    ephemeral_disk_size: 100
    hourly_billing_flag: true
    hostname_prefix: ((sl_vm_name_prefix))
    domain: ((sl_vm_domain))
    datacenter: ((sl_datacenter))
    sshKey: ((sl_public_ssh_key))

disk_types:
- name: default
  disk_size: 100_000
  cloud_properties:
    iops: 3000
    snapshot_space: 10
- name: small
  disk_size: 20_000
  cloud_properties:
    iops: 500
    snapshot_space: 5
- name: large
  disk_size: 250_000
  cloud_properties:
    iops: 3000
    snapshot_space: 50

networks:
- name: default
  type: dynamic
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    azs: [z1]
    dns: [((powerdns_ip)), 8.8.8.8, 10.0.80.11, 10.0.80.12]
    static: ((internal_static_ips))
    reserved: ((internal_reserved_ips))
    cloud_properties:
      vlan_ids: [((sl_vlan_public)), ((sl_vlan_private))]

- name: dynamic_public
  type: dynamic
  subnets:
  - cloud_properties:
      vlan_ids: [((sl_vlan_public_id))]
    dns: [((powerdns_ip)), 8.8.8.8, 10.0.80.11, 10.0.80.12]
    azs: [z1]

- name: dynamic_private
  type: dynamic
  subnets:
  - cloud_properties:
      vlan_ids: [((sl_vlan_private_id))]
    dns: [((powerdns_ip)), 8.8.8.8, 10.0.80.11, 10.0.80.12]
    azs: [z1]

- name: dynamic
  type: dynamic
  subnets:
  - cloud_properties:
      vlan_ids: [((sl_vlan_public_id)), ((sl_vlan_private_id))]
    dns: [((powerdns_ip)), 8.8.8.8, 10.0.80.11, 10.0.80.12]
    azs: [z1]

compilation:
  workers: 5
  reuse_compilation_vms: true
  vm_type: default
  network: dynamic
  az: z1
